spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: authservice
          uri: ${services.authservice-url}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authservice
                fallbackUri: forward:/fallback
        - id: userservice
          uri: ${services.userservice-url}
          predicates:
            - Path=/api/users/**,/api/cards/**
          filters:
            - name: CircuitBreaker
              args:
                name: userservice
                fallbackUri: forward:/fallback
        - id: orderservice
          uri: ${services.orderservice-url}
          predicates:
            - Path=/api/v1/orders/**,/api/v1/items/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderservice
                fallbackUri: forward:/fallback

services:
  authservice-url: http://localhost:8082
  userservice-url: http://localhost:8081
  orderservice-url: http://localhost:8080

jwt:
  secret: ${JWT_SECRET:}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

security:
  auth:
    login-path: /api/v1/auth/login
    register-path: /api/v1/auth/register

server:
  port: 8085
